// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.config;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import com.model.Role;
import com.model.User;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class CustomUserDetails_CustomUserDetails_6153a0c4b2_Test {

    private CustomUserDetails customUserDetails;
    private User mockUser;

    @BeforeEach
    public void setup() {
        mockUser = mock(User.class);
        customUserDetails = new CustomUserDetails(mockUser);
    }

    @Test
    public void testCustomUserDetails() {
        assertNotNull(customUserDetails);
    }

    @Test
    public void testGetUser() {
        assertEquals(mockUser, customUserDetails.getUser());
    }
}
