// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.config;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class CustomAdminDetails_isEnabled_6732b09672_Test {

    @Test
    public void testIsEnabled() {
        CustomAdminDetails customAdminDetails = new CustomAdminDetails();
        Assertions.assertTrue(customAdminDetails.isEnabled());
    }

    @Test
    public void testIsEnabled_False() {
        CustomAdminDetails customAdminDetails = new CustomAdminDetails();
        customAdminDetails.setEnabled(false);
        Assertions.assertFalse(customAdminDetails.isEnabled());
    }
}
