// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.config;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import com.model.Admin;
import com.model.Role;
import com.model.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class CustomAdminDetails_getPassword_ec5cf08305_Test {

    @InjectMocks
    Admin adm;

    @Mock
    UserDetails userDetails;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetPassword() {
        when(adm.getPassword()).thenReturn("adminPass");
        String password = adm.getPassword();
        assertEquals("adminPass", password);
    }

    @Test
    public void testGetPasswordFailure() {
        when(adm.getPassword()).thenReturn("wrongPass");
        String password = adm.getPassword();
        assertEquals("adminPass", password);
    }
}
