// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.config;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import com.model.Admin;
import com.model.Role;
import com.model.User;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = {Admin.class, Role.class, User.class})
public class CustomAdminDetails_isAccountNonLocked_f7b514125a_Test {

    @Autowired
    private Admin admin;

    @Test
    public void testIsAccountNonLockedSuccess() {
        Assert.assertTrue(admin.isAccountNonLocked());
    }

    @Test
    public void testIsAccountNonLockedFailure() {
        // TODO: Change the return value of isAccountNonLocked() method in Admin class to false to make this test case pass.
        Assert.assertFalse(admin.isAccountNonLocked());
    }
}
