// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.config;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import com.model.Role;
import com.model.User;

public class CustomUserDetails_getUsername_0a6d3fd936_Test {

    @Autowired
    private UserDetails userDetails;

    @Test
    public void testGetUsername() {
        User user = new User();
        user.setEmail("test@example.com");
        userDetails = new CustomUserDetails(user);
        String expected = "test@example.com";
        String actual = userDetails.getUsername();
        assertEquals(expected, actual);
    }

    @Test
    public void testGetUsernameWithEmptyEmail() {
        User user = new User();
        user.setEmail("");
        userDetails = new CustomUserDetails(user);
        String expected = "";
        String actual = userDetails.getUsername();
        assertEquals(expected, actual);
    }
}
