// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.config;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import com.model.Role;
import com.model.User;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertFalse;

public class CustomUserDetails_isAccountNonLocked_f7b514125a_Test {

    @Autowired
    private UserDetails userDetails;

    @Test
    public void testIsAccountNonLocked() {
        boolean result = userDetails.isAccountNonLocked();
        assertTrue(result, "Expected account to be non-locked but it was locked");
    }

    @Test
    public void testIsAccountLocked() {
        boolean result = userDetails.isAccountNonLocked();
        assertFalse(result, "Expected account to be locked but it was non-locked");
    }
}
