// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.config;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertFalse;

public class CustomUserDetails_isEnabled_6732b09672_Test {

    @Test
    public void testIsEnabledSuccess() {
        CustomUserDetails customUserDetails = new CustomUserDetails();
        boolean result = customUserDetails.isEnabled();
        assertTrue(result, "isEnabled method should return true");
    }
    
    @Test
    public void testIsEnabledFailure() {
        CustomUserDetails customUserDetails = new CustomUserDetails();
        boolean result = customUserDetails.isEnabled();
        assertFalse(result, "isEnabled method should return false");
    }
}
