// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.config;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.mockito.Mockito.when;

public class CustomAdminDetails_isAccountNonExpired_1875f479de_Test {
  
    @Mock
    private Admin admin;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testIsAccountNonExpired_true() {
        when(admin.isAccountNonExpired()).thenReturn(true);
        assertTrue(admin.isAccountNonExpired());
    }

    @Test
    public void testIsAccountNonExpired_false() {
        when(admin.isAccountNonExpired()).thenReturn(false);
        assertFalse(admin.isAccountNonExpired());
    }
}
