// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.security.authentication.dao.DaoAuthenticationProvider;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;

@RunWith(MockitoJUnitRunner.class)
public class MyConfig_configure_0ce24f1667_Test {

    @InjectMocks
    MyConfig myConfig;

    @Mock
    DaoAuthenticationProvider authenticationProvider1;

    @Mock
    DaoAuthenticationProvider authenticationProvider2;

    @Mock
    AuthenticationManagerBuilder auth;

    @Test
    public void testConfigure() throws Exception {
        myConfig.configure(auth);
        Mockito.verify(auth).authenticationProvider(authenticationProvider1);
        Mockito.verify(auth).authenticationProvider(authenticationProvider2);
    }

    @Test(expected = Exception.class)
    public void testConfigure_ThrowsException() throws Exception {
        Mockito.doThrow(new Exception()).when(auth).authenticationProvider(authenticationProvider1);
        myConfig.configure(auth);
    }
}
