// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.beans.factory.annotation.Autowired;

@ExtendWith(SpringExtension.class)
@SpringBootTest
public class Admin_getName_8400ac6fb7_Test {

    @Autowired
    private Admin admin;

    @Test
    public void testGetName_Success() {
        admin.setName("John Doe");
        String name = admin.getName();
        Assertions.assertEquals("John Doe", name, "Name should be John Doe");
    }

    @Test
    public void testGetName_Failure() {
        admin.setName("Jane Doe");
        String name = admin.getName();
        Assertions.assertNotEquals("John Doe", name, "Name should not be John Doe");
    }
}
