// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Admin_toString_ceffa8036e_Test {

    @Test
    public void testToString() {
        Admin admin = new Admin();
        admin.setId(1);
        admin.setName("John Doe");
        admin.setPassword("password123");
        List<Role> roles = new ArrayList<>();
        roles.add(new Role("ROLE_ADMIN"));
        admin.setRoles(roles);

        String expected = "Admin [id=1, name=John Doe, password=password123, roles=[Role [name=ROLE_ADMIN]]]";
        assertEquals(expected, admin.toString());
    }

    @Test
    public void testToStringWithoutRoles() {
        Admin admin = new Admin();
        admin.setId(1);
        admin.setName("Jane Doe");
        admin.setPassword("password123");

        String expected = "Admin [id=1, name=Jane Doe, password=password123, roles=[]]";
        assertEquals(expected, admin.toString());
    }
}
