// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

public class Admin_setId_17ddd86313_Test {

    @InjectMocks
    private Admin admin;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetIdPositive() {
        int id = 100;
        admin.setId(id);
        Assertions.assertEquals(id, admin.getId(), "The id set does not match the id retrieved.");
    }

    @Test
    public void testSetIdNegative() {
        int id = -50;
        admin.setId(id);
        Assertions.assertEquals(id, admin.getId(), "The id set does not match the id retrieved.");
    }

    @Test
    public void testSetIdZero() {
        int id = 0;
        admin.setId(id);
        Assertions.assertEquals(id, admin.getId(), "The id set does not match the id retrieved.");
    }
}
