// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Admin_getPassword_ec5cf08305_Test {

    @Test
    public void testGetPasswordSuccess() {
        Admin admin = new Admin();
        admin.setPassword("SecretPassword123");
        String expectedPassword = "SecretPassword123";
        assertEquals(expectedPassword, admin.getPassword());
    }

    @Test
    public void testGetPasswordFailure() {
        Admin admin = new Admin();
        admin.setPassword("SecretPassword123");
        String expectedPassword = "WrongPassword";
        assertEquals(expectedPassword, admin.getPassword());
    }
}
