// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@SpringBootTest
public class Admin_getRoles_dd524a1aa8_Test {

    @MockBean
    private Admin admin;

    private List<Role> roles;

    @BeforeEach
    void setUp() {
        roles = new ArrayList<>();
        roles.add(new Role("ROLE_USER"));
        roles.add(new Role("ROLE_ADMIN"));

        when(admin.getRoles()).thenReturn(roles);
    }

    @Test
    public void testGetRolesSuccess() {
        assertEquals(roles, admin.getRoles());
    }

    @Test
    public void testGetRolesFailure() {
        List<Role> wrongRoles = new ArrayList<>();
        wrongRoles.add(new Role("ROLE_GUEST"));

        assertNotEquals(wrongRoles, admin.getRoles());
    }
}
