// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Admin_Admin_8160688bfa_Test {

    @Test
    public void testAdminConstructorSuccess() {
        Admin admin = new Admin();
        assertNotNull(admin, "Admin object should not be null");
    }

    @Test
    public void testAdminConstructorFailure() {
        Admin admin = null;
        assertNull(admin, "Admin object should be null");
    }
}
