// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Admin_setPassword_19d13444f4_Test {

    @InjectMocks
    private Admin admin;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetPassword_Success() {
        String expectedPassword = "password1234";
        admin.setPassword(expectedPassword);
        assertEquals(expectedPassword, admin.getPassword());
    }

    @Test
    public void testSetPassword_Null() {
        String expectedPassword = null;
        admin.setPassword(expectedPassword);
        assertEquals(expectedPassword, admin.getPassword());
    }
}
