// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;
import java.util.ArrayList;
import java.util.List;

@SpringBootTest
public class Admin_Admin_ddc0adaa15_Test {

    private Admin admin;
    private List<Role> roles;

    @BeforeEach
    public void setup() {
        roles = new ArrayList<>();
        roles.add(new Role(1, "ADMIN"));
        roles.add(new Role(2, "USER"));
    }

    @Test
    public void testAdminConstructor() {
        admin = new Admin(1, "Test Admin", "password123", roles);

        assertEquals(1, admin.getId());
        assertEquals("Test Admin", admin.getName());
        assertEquals("password123", admin.getPassword());
        assertEquals(roles, admin.getRoles());
    }

    @Test
    public void testAdminConstructorWithEmptyRoles() {
        admin = new Admin(1, "Test Admin", "password123", new ArrayList<>());

        assertEquals(1, admin.getId());
        assertEquals("Test Admin", admin.getName());
        assertEquals("password123", admin.getPassword());
        assertEquals(new ArrayList<>(), admin.getRoles());
    }
}
