// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

public class Candidate_setId_17ddd86313_Test {

    @InjectMocks
    private Candidate candidate;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetIdPositive() {
        int expectedId = 10;
        candidate.setId(expectedId);
        Assertions.assertEquals(expectedId, candidate.getId(), "The set ID does not match the expected ID");
    }

    @Test
    public void testSetIdNegative() {
        int expectedId = -10;
        candidate.setId(expectedId);
        Assertions.assertEquals(expectedId, candidate.getId(), "The set ID does not match the expected ID");
    }

    @Test
    public void testSetIdZero() {
        int expectedId = 0;
        candidate.setId(expectedId);
        Assertions.assertEquals(expectedId, candidate.getId(), "The set ID does not match the expected ID");
    }
}
