// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(MockitoExtension.class)
public class Candidate_setCandidate3_187fe040d7_Test {

    @InjectMocks
    private Candidate candidate;

    @BeforeEach
    void setUp() {
        candidate = new Candidate();
    }

    @Test
    public void testSetCandidate3_success() {
        String expectedCandidate3 = "John Doe";
        candidate.setCandidate3(expectedCandidate3);
        assertEquals(expectedCandidate3, candidate.getCandidate3());
    }

    @Test
    public void testSetCandidate3_null() {
        String expectedCandidate3 = null;
        candidate.setCandidate3(expectedCandidate3);
        assertEquals(expectedCandidate3, candidate.getCandidate3());
    }
}
