// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import static org.junit.Assert.assertEquals;
import org.junit.Before;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class Candidate_getCandidate2_6fd06ef279_Test {

    @InjectMocks
    Candidate candidate;

    @Before
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetCandidate2_Success() {
        String expected = "John Doe";
        candidate.setCandidate2(expected);
        String actual = candidate.getCandidate2();
        assertEquals(expected, actual);
    }

    @Test
    public void testGetCandidate2_Failure() {
        String unexpected = "Jane Doe";
        candidate.setCandidate2("John Doe");
        String actual = candidate.getCandidate2();
        assertNotEquals(unexpected, actual);
    }
}
