// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Candidate_Candidate_db2d02c985_Test {

    private Candidate candidate;

    @BeforeEach
    public void setup() {
        candidate = new Candidate(1, "John", "Jane", "Joe", "June");
    }

    @Test
    public void testCandidateId() {
        assertEquals(1, candidate.getId(), "Candidate Id should be 1");
    }

    @Test
    public void testCandidate1() {
        assertEquals("John", candidate.getCandidate1(), "Candidate1 should be John");
    }

    @Test
    public void testCandidate2() {
        assertEquals("Jane", candidate.getCandidate2(), "Candidate2 should be Jane");
    }

    @Test
    public void testCandidate3() {
        assertEquals("Joe", candidate.getCandidate3(), "Candidate3 should be Joe");
    }

    @Test
    public void testCandidate4() {
        assertEquals("June", candidate.getCandidate4(), "Candidate4 should be June");
    }
}
