// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(MockitoExtension.class)
public class Candidate_setCandidate2_6ecd8693ac_Test {

    @InjectMocks
    private Candidate candidate;

    @Test
    public void testSetCandidate2_Success() {
        String expectedCandidate2 = "John Doe";
        candidate.setCandidate2(expectedCandidate2);
        assertEquals(expectedCandidate2, candidate.getCandidate2());
    }

    @Test
    public void testSetCandidate2_Null() {
        String expectedCandidate2 = null;
        candidate.setCandidate2(expectedCandidate2);
        assertEquals(expectedCandidate2, candidate.getCandidate2());
    }
}
