// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Candidate_toString_ceffa8036e_Test {

    @Test
    public void testToString() {
        Candidate candidate = new Candidate();
        candidate.setId(1);
        candidate.setCandidate1("John");
        candidate.setCandidate2("Doe");
        candidate.setCandidate3("Jane");
        candidate.setCandidate4("Doe");
        
        String expected = "Candidate [id=1, candidate1=John, candidate2=Doe, candidate3=Jane, candidate4=Doe]";
        String actual = candidate.toString();
        
        assertEquals(expected, actual);
    }
    
    @Test
    public void testToStringWithNullValues() {
        Candidate candidate = new Candidate();
        
        String expected = "Candidate [id=null, candidate1=null, candidate2=null, candidate3=null, candidate4=null]";
        String actual = candidate.toString();
        
        assertEquals(expected, actual);
    }
}
