// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Candidate_setCandidate4_2c81d80cfe_Test {

    @InjectMocks
    Candidate candidate;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetCandidate4() {
        String expectedValue = "John Doe";
        candidate.setCandidate4(expectedValue);
        assertEquals(expectedValue, candidate.getCandidate4());
    }

    @Test
    public void testSetCandidate4_nullValue() {
        candidate.setCandidate4(null);
        assertEquals(null, candidate.getCandidate4());
    }
}
