// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Role_Role_ec1b84f490_Test {

    @Test
    public void testRoleConstructor() {
        Role role = new Role();
        assertNotNull(role);
    }

    @Test
    public void testRoleConstructorWithParameters() {
        Role role = new Role("Admin");
        assertNotNull(role);
        assertEquals("Admin", role.getRoleName());
    }
}
