// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

@SpringBootTest
public class Role_getName_8400ac6fb7_Test {

    private Role role;

    @BeforeEach
    public void setUp() {
        role = Mockito.mock(Role.class);
    }

    @Test
    public void testGetName() {
        Mockito.when(role.getName()).thenReturn("Admin");
        String result = role.getName();
        Assertions.assertEquals("Admin", result);
    }

    @Test
    public void testGetNameFailure() {
        Mockito.when(role.getName()).thenReturn(null);
        String result = role.getName();
        Assertions.assertNull(result);
    }
}
