// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Role_setName_5d23a892d9_Test {

    @MockBean
    private Role role;

    @Test
    public void setNameTest() {
        String expectedName = "Admin";
        role.setName(expectedName);
        assertEquals(expectedName, role.getName());
    }

    @Test
    public void setNameEmptyStringTest() {
        String expectedName = "";
        role.setName(expectedName);
        assertEquals(expectedName, role.getName());
    }
}
