// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

@SpringBootTest
public class Role_setId_17ddd86313_Test {

    @MockBean
    private Role role;

    @BeforeEach
    public void setUp() {
        role = new Role();
    }

    @Test
    public void testSetId_PositiveNumber() {
        role.setId(1);
        Assertions.assertEquals(1, role.getId(), "When a positive number is used to set id, it must return the same number as id");
    }

    @Test
    public void testSetId_Zero() {
        role.setId(0);
        Assertions.assertEquals(0, role.getId(), "When 0 is used to set id, it must return 0 as id");
    }

    @Test
    public void testSetId_NegativeNumber() {
        role.setId(-1);
        Assertions.assertEquals(-1, role.getId(), "When a negative number is used to set id, it must return the same number as id");
    }
}
