// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Role_Role_0e7602478c_Test {

    private Role role;
    private List<User> users;
    private List<Admin> admins;

    @BeforeEach
    public void setUp() {
        User user = new User(1, "John", "john@example.com");
        Admin admin = new Admin(1, "Admin1", "admin1@example.com");
        users = Arrays.asList(user);
        admins = Arrays.asList(admin);
    }

    @Test
    public void testRole() {
        role = new Role(1, "ROLE_USER", users, admins);
        assertEquals(1, role.getId());
        assertEquals("ROLE_USER", role.getName());
        assertEquals(users, role.getUsers());
        assertEquals(admins, role.getAdmins());
    }

    @Test
    public void testRoleWithEmptyUsersAndAdmins() {
        role = new Role(1, "ROLE_USER", null, null);
        assertEquals(1, role.getId());
        assertEquals("ROLE_USER", role.getName());
        assertEquals(null, role.getUsers());
        assertEquals(null, role.getAdmins());
    }
}
