// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import java.util.Arrays;
import java.util.List;

public class Role_getAdmins_a7babdc2bd_Test {

    @InjectMocks
    Role role;

    @Mock
    List<Admin> admins;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetAdminsSuccess() {
        Admin admin1 = new Admin();
        admin1.setName("John");
        Admin admin2 = new Admin();
        admin2.setName("Doe");
        when(admins.get(0)).thenReturn(admin1);
        when(admins.get(1)).thenReturn(admin2);
        role.setAdmins(admins);
        List<Admin> result = role.getAdmins();
        assertEquals(admin1, result.get(0));
        assertEquals(admin2, result.get(1));
    }

    @Test
    public void testGetAdminsEmpty() {
        when(admins.isEmpty()).thenReturn(true);
        role.setAdmins(admins);
        List<Admin> result = role.getAdmins();
        assertEquals(true, result.isEmpty());
    }
}
