// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Role_toString_ceffa8036e_Test {
    
    private Role role;

    @BeforeEach
    public void setUp() {
        role = new Role();
    }

    @Test
    public void testToString() {
        role.setId(1L);
        role.setName("Admin");
        role.setUsers(List.of(new User("User1"), new User("User2")));
        role.setAdmins(List.of(new Admin("Admin1"), new Admin("Admin2")));

        String expected = "Role [id=1, name=Admin, users=[User1, User2], admins=[Admin1, Admin2]]";
        String actual = role.toString();

        assertEquals(expected, actual);
    }

    @Test
    public void testToString_EmptyRole() {
        String expected = "Role [id=null, name=null, users=null, admins=null]";
        String actual = role.toString();

        assertEquals(expected, actual);
    }
}
