// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class User_toString_ceffa8036e_Test {

    private User user;

    @BeforeEach
    public void setUp() {
        user = new User();
        user.setId(1);
        user.setName("Test User");
        user.setPassword("testPassword");
        user.setEmail("test@test.com");
        user.setPhone("1234567890");

        List<Role> roles = new ArrayList<>();
        Role role = new Role();
        role.setId(1);
        role.setName("ROLE_USER");
        roles.add(role);

        user.setRoles(roles);
    }

    @Test
    public void testToString() {
        String expected = "User [id=1, name=Test User, password=testPassword, email=test@test.com, phone=1234567890, roles=[Role [id=1, name=ROLE_USER]]]";
        assertEquals(expected, user.toString());
    }

    @Test
    public void testToStringWithNoRoles() {
        user.setRoles(null);
        String expected = "User [id=1, name=Test User, password=testPassword, email=test@test.com, phone=1234567890, roles=null]";
        assertEquals(expected, user.toString());
    }
}
