// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class User_setPhone_0adff8dec5_Test {

    private User user;

    @BeforeEach
    public void setUp() {
        user = Mockito.mock(User.class);
    }

    @Test
    public void testSetPhone_PositiveCase() {
        int expectedPhone = 1234567890;
        Mockito.doAnswer(invocation -> {
            Integer phone = invocation.getArgument(0);
            assertEquals(expectedPhone, phone);
            return null;
        }).when(user).setPhone(Mockito.anyInt());

        user.setPhone(expectedPhone);
    }

    @Test
    public void testSetPhone_NegativeCase() {
        int unexpectedPhone = 987654321;
        Mockito.doAnswer(invocation -> {
            Integer phone = invocation.getArgument(0);
            assertNotEquals(unexpectedPhone, phone);
            return null;
        }).when(user).setPhone(Mockito.anyInt());

        user.setPhone(1234567890);
    }
}
