// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class User_setEmail_d1f6d493ae_Test {

    private User user;

    @BeforeEach
    public void setup() {
        user = new User();
    }

    @Test
    public void testSetEmail_Success() {
        String email = "test@example.com";
        user.setEmail(email);
        Assertions.assertEquals(email, user.getEmail());
    }

    @Test
    public void testSetEmail_Null() {
        String email = null;
        user.setEmail(email);
        Assertions.assertNull(user.getEmail());
    }
}
