// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

public class User_setPassword_19d13444f4_Test {

    @InjectMocks
    User user;

    @Before
    public void setUp() throws Exception {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetPassword() {
        String password = "password123";
        user.setPassword(password);
        Assert.assertEquals(password, user.getPassword());
    }

    @Test
    public void testSetPassword_EmptyPassword() {
        String password = "";
        user.setPassword(password);
        Assert.assertEquals(password, user.getPassword());
    }

    @Test
    public void testSetPassword_NullPassword() {
        String password = null;
        user.setPassword(password);
        Assert.assertNull(user.getPassword());
    }
}
