// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class User_getPhone_a03761c8d8_Test {

    @Test
    public void testGetPhoneSuccess() {
        User user = new User();
        user.setPhone(1234567890);
        assertEquals(1234567890, user.getPhone());
    }

    @Test
    public void testGetPhoneFailure() {
        User user = new User();
        user.setPhone(1234567890);
        assertEquals(0987654321, user.getPhone());
    }
}
