// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

class User_setId_17ddd86313_Test {

    private User user;
    
    @BeforeEach
    void setUp() {
        user = new User();
    }

    @Test
    public void testSetId_positive() {
        int expectedId = 1;
        user.setId(expectedId);
        assertEquals(expectedId, user.getId(), "The ID set in the user object does not match the expected ID");
    }

    @Test
    public void testSetId_zero() {
        int expectedId = 0;
        user.setId(expectedId);
        assertEquals(expectedId, user.getId(), "The ID set in the user object does not match the expected ID");
    }
    
    @Test
    public void testSetId_negative() {
        int expectedId = -1;
        user.setId(expectedId);
        assertEquals(expectedId, user.getId(), "The ID set in the user object does not match the expected ID");
    }
}
