// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class User_getEmail_7b79ef55db_Test {

    @Test
    public void testGetEmailSuccess() {
        User user = new User();
        user.setEmail("test@example.com");
        String expectedEmail = "test@example.com";
        String actualEmail = user.getEmail();
        Assertions.assertEquals(expectedEmail, actualEmail, "The emails should match");
    }

    @Test
    public void testGetEmailFailure() {
        User user = new User();
        user.setEmail("test@example.com");
        String expectedEmail = "wrong@example.com";
        String actualEmail = user.getEmail();
        Assertions.assertNotEquals(expectedEmail, actualEmail, "The emails should not match");
    }
}
