// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class User_getName_8400ac6fb7_Test {

    private User user;

    @BeforeEach
    public void setup() {
        user = new User();
    }

    @Test
    public void testGetName_WhenNameExists() {
        String expectedName = "John Doe";
        user.setName(expectedName);
        String actualName = user.getName();
        assertEquals(expectedName, actualName, "The name returned did not match the expected value");
    }

    @Test
    public void testGetName_WhenNameIsNull() {
        String expectedName = null;
        user.setName(expectedName);
        String actualName = user.getName();
        assertEquals(expectedName, actualName, "The name returned did not match the expected value (null)");
    }
}
