// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class User_setName_5d23a892d9_Test {

    private User user;

    @BeforeEach
    public void setUp() {
        user = new User();
    }

    @Test
    public void testSetName() {
        String expectedName = "Test User";
        user.setName(expectedName);
        assertEquals(expectedName, user.getName(), "The name set does not match the expected name");
    }
    
    @Test
    public void testSetName_Empty() {
        String expectedName = "";
        user.setName(expectedName);
        assertEquals(expectedName, user.getName(), "The name set does not match the expected name");
    }

    @Test
    public void testSetName_Null() {
        String expectedName = null;
        user.setName(expectedName);
        assertEquals(expectedName, user.getName(), "The name set does not match the expected name");
    }
}
